// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA878UAS5AtZHue7OYay-kDoXPe9PEm2ik',
    appId: '1:507082849019:web:709cf186d8eaf3b3a14e5e',
    messagingSenderId: '507082849019',
    projectId: 'ecommerce-f6aad',
    authDomain: 'ecommerce-f6aad.firebaseapp.com',
    storageBucket: 'ecommerce-f6aad.appspot.com',
    measurementId: 'G-6VLJ6SHLR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyq0T-lmwIT0x1c-QLyQbuw0ENw7Y8eoY',
    appId: '1:507082849019:android:f6d2e044fc6ec388a14e5e',
    messagingSenderId: '507082849019',
    projectId: 'ecommerce-f6aad',
    storageBucket: 'ecommerce-f6aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo1FeLTSxxF-pLBlQVELkcgSVRQhZQ1_Q',
    appId: '1:507082849019:ios:260d1a8887780777a14e5e',
    messagingSenderId: '507082849019',
    projectId: 'ecommerce-f6aad',
    storageBucket: 'ecommerce-f6aad.appspot.com',
    iosBundleId: 'com.example.wacSports',
  );
}
